<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use App\Models\Vegetable;
use App\Models\Store;
use App\Models\Trunk;
use App\Models\TrunkStatus;

class RealSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now()->toDateTimeString();
        DB::table('admins')->truncate();
        DB::table('devices')->truncate();
        DB::table('stores')->truncate();
        DB::table('users')->truncate();
        DB::table('partners')->truncate();
        DB::table('device_categories')->truncate();
        DB::table('vegetable_categories')->truncate();
        DB::table('vegetables')->truncate();
        DB::table('vegetable_in_store')->truncate();
        DB::table('trunks')->truncate();
        DB::table('trunk_status')->truncate();
        DB::table('images')->truncate();

        DB::table('admins')->insert([
            [
                'id' => 1,
                'name' => 'hoanghoi-admin',
                'email' => 'hoanghoi1310@gmail.com',
                'phone_number' => '0982-708-092',
                'is_super' => 1,
                'password' => bcrypt('12344321'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        DB::table('partners')->insert([
            [
                'id' => 1,
                'name' => 'hoanghoi-partner',
                'email' => 'hoanghoi1310@gmail.com',
                'phone_number' => '0982-708-802',
                'password' => bcrypt('12344321'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'hoanghoi-user',
                'email' => 'hoanghoi1310@gmail.com',
                'phone_number' => '0982-708-072',
                'password' => bcrypt('12344321'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        DB::table('stores')->insert([
            [
                'id' => 1,
                'partner_id' => 1,
                'logo' => '',
                'phone_number' => '0982-563-574',
                'name' => 'Cửa hàng rau sạch Định Công',
                'address' => 'Ngõ 175 Định Công, Hoàng Mai, Hà Nội',
                'info' => 'Cửa hàng rau sạch Định Công chuyên cung cấp các loại rau củ chất lượng tốt, trồng trên giàn thủy canh, không sâu bệnh, không thuốc bảo vệ thực vật, giá cả hợp lý, an toàn cho mọi gia đình.',
                'latitude' => 20.9813732,
                'longitude' => 105.8370336,
                'is_actived' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'partner_id' => 1,
                'logo' => '',
                'phone_number' => '0972-563-574',
                'name' => 'Cửa hàng rau sạch Royal City',
                'address' => '72 Nguyễn Trãi, Khu đô thị Royal City, Thượng Đình, Thanh Xuân, Hà Nội',
                'info' => 'Cửa hàng rau sạch Khu đô thị Royal City chuyên cung cấp các loại rau củ chất lượng tốt, trồng trên giàn thủy canh, không sâu bệnh, không thuốc bảo vệ thực vật, giá cả hợp lý, an toàn cho mọi gia đình.',
                'latitude' => 21.002071,
                'longitude' => 105.816675,
                'is_actived' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'partner_id' => 1,
                'logo' => '',
                'phone_number' => '0984-763-274',
                'name' => 'Cửa hàng rau sạch Trường Chinh',
                'address' => '361 Trường Chinh, Khương Trung, Thanh Xuân, Hà Nội',
                'info' => 'Cửa hàng rau sạch Trường Chinh chuyên cung cấp các loại rau củ chất lượng tốt, trồng trên giàn thủy canh, không sâu bệnh, không thuốc bảo vệ thực vật, giá cả hợp lý, an toàn cho mọi gia đình.',
                'latitude' => 21.002021,
                'longitude' => 105.821557,
                'is_actived' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'partner_id' => 1,
                'logo' => '',
                'phone_number' => '0961-562-574',
                'name' => 'Cửa hàng rau sạch Tây Sơn',
                'address' => 'Tòa nhà Mipec, 229, Tây Sơn, Phường Ngã Tư Sở, Quận Đống Đa, Đống Đa, Hà Nội, Vietnam',
                'info' => 'Cửa hàng rau sạch Tây Sơn chuyên cung cấp các loại rau củ chất lượng tốt, trồng trên giàn thủy canh, không sâu bệnh, không thuốc bảo vệ thực vật, giá cả hợp lý, an toàn cho mọi gia đình.',
                'latitude' => 21.005376,
                'longitude' => 105.823799,
                'is_actived' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'partner_id' => 1,
                'logo' => '',
                'phone_number' => '0982-563-574',
                'name' => 'Cửa hàng rau sạch Phạm Ngọc Thạch',
                'address' => 'Ngõ 65 Phạm Ngọc Thạch, Đống Đa, Hà Nội, Vietnam',
                'info' => 'Cửa hàng rau sạch Phạm Ngọc Thạch chuyên cung cấp các loại rau củ chất lượng tốt, trồng trên giàn thủy canh, không sâu bệnh, không thuốc bảo vệ thực vật, giá cả hợp lý, an toàn cho mọi gia đình.',
                'latitude' => 21.008832,
                'longitude' => 105.834603,
                'is_actived' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'partner_id' => 1,
                'logo' => '',
                'phone_number' => '0982-563-574',
                'name' => 'Cửa hàng rau sạch Khương Trung',
                'address' => '361 Trường Chinh, Khương Trung, Thanh Xuân, Hà Nội, Vietnam',
                'info' => 'Cửa hàng rau sạch Khương Trung chuyên cung cấp các loại rau củ chất lượng tốt, trồng trên giàn thủy canh, không sâu bệnh, không thuốc bảo vệ thực vật, giá cả hợp lý, an toàn cho mọi gia đình.',
                'latitude' => 21.001881,
                'longitude' => 105.821589,
                'is_actived' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'partner_id' => 1,
                'logo' => '',
                'phone_number' => '0982-563-574',
                'name' => 'Cửa hàng rau sạch Ngõ Xã Đàn',
                'address' => '51 Ngõ Xã Đàn II, Nam Đồng, Đống Đa, Hà Nội',
                'info' => 'Cửa hàng rau sạch Ngõ Xã Đàn chuyên cung cấp các loại rau củ chất lượng tốt, trồng trên giàn thủy canh, không sâu bệnh, không thuốc bảo vệ thực vật, giá cả hợp lý, an toàn cho mọi gia đình.',
                'latitude' => 21.014951,
                'longitude' => 105.833187,
                'is_actived' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'partner_id' => 1,
                'logo' => '',
                'phone_number' => '0982-563-574',
                'name' => 'Cửa hàng rau sạch Đại Cồ Việt',
                'address' => '51A, Đại Cồ Việt, Quận Hai Bà Trưng, Bách Khoa, Hai Bà Trưng, Hà Nội',
                'info' => 'Cửa hàng rau sạch Đại Cồ Việt chuyên cung cấp các loại rau củ chất lượng tốt, trồng trên giàn thủy canh, không sâu bệnh, không thuốc bảo vệ thực vật, giá cả hợp lý, an toàn cho mọi gia đình.',
                'latitude' => 21.008060,
                'longitude' => 105.847392,
                'is_actived' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'partner_id' => 1,
                'logo' => '',
                'phone_number' => '0982-563-574',
                'name' => 'Cửa hàng rau sạch Bà Triệu',
                'address' => '157 Bà Triệu, Bùi Thị Xuân, Hai Bà Trưng, Hà Nội',
                'info' => 'Cửa hàng rau sạch Định Công chuyên cung cấp các loại rau củ chất lượng tốt, trồng trên giàn thủy canh, không sâu bệnh, không thuốc bảo vệ thực vật, giá cả hợp lý, an toàn cho mọi gia đình.',
                'latitude' => 21.013349,
                'longitude' => 105.849431,
                'is_actived' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'partner_id' => 1,
                'logo' => '',
                'phone_number' => '0982-563-574',
                'name' => 'Cửa hàng rau sạch Ngô Thì Nhậm',
                'address' => '58 Ngô Thì Nhậm, Hai Bà Trưng, Hà Nội',
                'info' => 'Cửa hàng rau sạch Ngô Thì Nhậm chuyên cung cấp các loại rau củ chất lượng tốt, trồng trên giàn thủy canh, không sâu bệnh, không thuốc bảo vệ thực vật, giá cả hợp lý, an toàn cho mọi gia đình.',
                'latitude' => 21.016606,
                'longitude' => 105.852793,
                'is_actived' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'partner_id' => 1,
                'logo' => '',
                'phone_number' => '0982-563-574',
                'name' => 'Cửa hàng rau sạch Lê Duẩn',
                'address' => '177 Lê Duẩn, Nguyễn Du, Đống Đa, Hà Nội',
                'info' => 'Cửa hàng rau sạch Lê Duẩn chuyên cung cấp các loại rau củ chất lượng tốt, trồng trên giàn thủy canh, không sâu bệnh, không thuốc bảo vệ thực vật, giá cả hợp lý, an toàn cho mọi gia đình.',
                'latitude' => 21.020339,
                'longitude' => 105.841534,
                'is_actived' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'partner_id' => 1,
                'logo' => '',
                'phone_number' => '0982-563-574',
                'name' => 'Cửa hàng rau sạch Thành Công',
                'address' => '21 Thành Công, Ba Đình, Hà Nội',
                'info' => 'Cửa hàng rau sạch Thành Công chuyên cung cấp các loại rau củ chất lượng tốt, trồng trên giàn thủy canh, không sâu bệnh, không thuốc bảo vệ thực vật, giá cả hợp lý, an toàn cho mọi gia đình.',
                'latitude' => 21.023744,
                'longitude' => 105.816343,
                'is_actived' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        DB::table('device_categories')->insert([
            [
                'id' => 1,
                'name' => 'Cảm biến',
                'symbol' => 'C',
                'description' => 'Thiết bị đo điều kiện môi trường xung quanh',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'Máy bơm',
                'symbol' => 'B',
                'description' => 'Thiết bị cung cấp chất dinh dưỡng cho giàn',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'Đèn',
                'symbol' => 'D',
                'description' => 'Thiết bị chiếu sáng cho giàn',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'Quạt gió',
                'symbol' => 'E',
                'description' => 'Thiết bị điều hòa gió cho giàn',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
        ]);
        DB::table('devices')->insert([
            // Cam bien
            [
                'id' => 1,
                'identify_code' => 'AAAAA0000000001',
                'name' => 'Cảm biến nhiệt độ nước',
                'password' => bcrypt('12344321'),
                'store_id' => 1,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'identify_code' => 'AAAAA0000000002',
                'name' => 'Cảm biến nhiệt độ không khí',
                'password' => bcrypt('12344321'),
                'store_id' => 1,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'identify_code' => 'AAAAA0000000003',
                'name' => 'Cảm biến PH',
                'password' => bcrypt('12344321'),
                'store_id' => 1,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // May bom
            [
                'id' => 4,
                'identify_code' => 'BBBBB0000000001',
                'name' => 'Máy bơm 0',
                'password' => bcrypt('12344321'),
                'store_id' => 1,
                'category_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'identify_code' => 'BBBBB0000000002',
                'name' => 'Máy bơm 1',
                'password' => bcrypt('12344321'),
                'store_id' => 1,
                'category_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'identify_code' => 'BBBBB0000000003',
                'name' => 'Máy bơm 2',
                'password' => bcrypt('12344321'),
                'store_id' => 1,
                'category_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Den
            [
                'id' => 7,
                'identify_code' => 'DDDDD0000000001',
                'name' => 'Đèn mạn trái',
                'password' => bcrypt('12344321'),
                'store_id' => 1,
                'category_id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'identify_code' => 'DDDDD0000000002',
                'name' => 'Đèn mạn phải',
                'password' => bcrypt('12344321'),
                'store_id' => 1,
                'category_id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            //Quat gio
            [
                'id' => 9,
                'identify_code' => 'EEEEE0000000001',
                'name' => 'Quạt gió chính',
                'password' => bcrypt('12344321'),
                'store_id' => 1,
                'category_id' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'identify_code' => 'EEEEE0000000002',
                'name' => 'Quạt gió phụ',
                'password' => bcrypt('12344321'),
                'store_id' => 1,
                'category_id' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // VegetableCategory
        DB::table('vegetable_categories')->insert([
            [
                'id' => 1,
                'name' => 'Rau sống',
                'description' => 'Rau thường để ăn sống',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'name' => 'Rau xanh',
                'description' => 'Rau thường được nấu chín và chế biến thành các món ăn khác nhau',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'name' => 'Rau cải',
                'description' => 'Các loại rau thuộc họ cải',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'name' => 'Gia vị',
                'description' => 'Gia vị, theo định nghĩa của các nhà khoa học và sinh học, là những loại thực phẩm, rau thơm (thường có tinh dầu) hoặc các hợp chất hóa học cho thêm vào món ăn, có thể tạo những kích thích tích cực nhất định lên cơ quan vị giác, khứu giác và thị giác đối với người ẩm thực.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'name' => 'Củ, quả',
                'description' => 'Củ, quả',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // Vegetable
        DB::table('vegetables')->insert([
            [
                'id' => 1,
                'category_id' => 1,
                'name' => 'Xà lách',
                'description' => 'Rau chứa rất nhiều muối khoáng giúp mang lại sự tinh thần và tránh được nhiều bệnh tật.',
                'price' => 10000,
                'is_actived' => true,
                'number_grow_day' => 60,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'category_id' => 2,
                'name' => 'Rau muống',
                'description' => 'Rau quen thuộc trong bữa ăn hàng ngày. Rau có tác dụng tốt, như: thanh nhiệt, giải độc, lợi tiểu,...',
                'price' => 10000,
                'is_actived' => true,
                'number_grow_day' => 60,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'category_id' => 2,
                'name' => 'Rau ngót',
                'description' => 'Ẩm thực Việt Nam dùng rau ngót nấu canh với thịt băm, hoặc có khi chỉ nấu suông vì rau có sẵn vị ngọt.',
                'price' => 10000,
                'is_actived' => true,
                'number_grow_day' => 60,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'category_id' => 3,
                'name' => 'Cải ngồng',
                'description' => 'Lọai rau đặc sản của khu vực miền Bắc. Ăn rau cải ngồng sẽ làm da dẻ mịn màng, tươi tắn, làm chậm quá trình lão hóa. Tăng sức đề kháng cho cơ thể.',
                'price' => 10000,
                'is_actived' => true,
                'number_grow_day' => 50,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'category_id' => 3,
                'name' => 'Cải ngọt',
                'description' => 'Cải ngọt thường được chế biến thành các món ăn như cải ngọt xào thịt, canh cải ngọt nấu tôm, rau cải ngọt luộc chấm xì dầu, cải ngọt xào thịt bò, cải ngọt xào chân gà..., làm lẩu cá, lẩu thịt.',
                'price' => 12000,
                'is_actived' => true,
                'number_grow_day' => 60,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'category_id' => 3,
                'name' => 'Cải bẹ xanh',
                'description' => 'Rau cải xanh chứa hàm lượng chất xơ rất lớn, chất nhầy. Chất nhầy sẽ hỗ trợ nhu động ruột, giúp tiêu hóa tốt hơn. Đồng thời, chất xơ giúp bạn ngăn ngừa táo bón.',
                'price' => 10000,
                'is_actived' => true,
                'number_grow_day' => 60,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'category_id' => 3,
                'name' => 'Cải thìa',
                'description' => 'Cải thìa tốt cho phụ nữ mang thai, có tác dụng phòng ngừa khuyết tật cho thai nhi, giúp xương chắc khỏe, có khả năng kích thích nhịp tim hoạt động tốt và hạ huyết áp. Cải thìa làm chậm quá trình lão hóa.',
                'price' => 10000,
                'is_actived' => true,
                'number_grow_day' => 60,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'category_id' => 2,
                'name' => 'Rau lang',
                'description' => 'Ăn rau lang xào tỏi rất tốt cho tiêu hóa. Cả củ và rau lang đều nhuận tràng, ăn nhiều trị được táo bón. Phụ nữ sau khi sinh có thể dùng ngọn hay lá rau lang nấu canh hoặc luộc ăn cho thêm sữa.',
                'price' => 10000,
                'is_actived' => true,
                'number_grow_day' => 70,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'category_id' => 1,
                'name' => 'Rau kinh giới',
                'description' => 'Rau kinh giới là loại rau gia vị phổ biến được sử dụng trong nhiều món ăn, trong rau có thành phần vitamin và khoáng chất, có thể điều trị được nhiều bệnh, kháng khuẩn và chống oxy hóa tốt.',
                'price' => 13000,
                'is_actived' => true,
                'number_grow_day' => 70,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'category_id' => 2,
                'name' => 'Mồng tơi',
                'description' => 'Mồng tơi là loại rau quen thuộc, được sử dụng để chế biến trong bữa ăn hàng ngày. rau mồng tơi có tính hàn, vị chua, tán nhiệt, mất máu, lợi tiểu, giải độc, đẹp da, trị rôm sảy mụn nhọt hiệu quả… rất thích hợp trong mùa nóng.',
                'price' => 14000,
                'is_actived' => true,
                'number_grow_day' => 60,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'category_id' => 3,
                'name' => 'Cải cúc',
                'description' => 'Cải cúc dễ chế biến, giàu dinh dưỡng và có tác dụng chữa bệnh tốt với một số bệnh thông thường. Cải cúc có tác dụng chữa các bệnh như ít sữa sau sinh, trị đau đầu, hoa mắt, ...',
                'price' => 10000,
                'is_actived' => true,
                'number_grow_day' => 50,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'category_id' => 4,
                'name' => 'Hành lá',
                'description' => 'Hành luôn được coi là thực phẩm có tính kháng viêm cao. Ngoài ra, nó lại rất giàu vitamin A, B, C và là một nguồn dinh dưỡng thiên nhiên tiềm năng cung cấp acid folic, canxi, phốt pho, magiê, crom, sắt và chất xơ.',
                'price' => 5000,
                'is_actived' => true,
                'number_grow_day' => 40,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'category_id' => 5,
                'name' => 'Củ cải trắng',
                'description' => 'Củ cải trắng là một món ăn phổ biến. Củ cải trắng tươi có vị cay, tính mát, khi nấu chín lại có vị ngọt, tính bình sở hữu công dụng thanh nhiệt, giải độc, kiện vị, tiêu thực, tiêu đờm, khỏi ho.',
                'price' => 15000,
                'is_actived' => true,
                'number_grow_day' => 80,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'category_id' => 4,
                'name' => 'Sả',
                'description' => 'Không chỉ là gia vị đặc trưng trong bếp, sả còn là vị thuốc quý. Đông y đánh giá cao tác dụng giải độc, hỗ trợ tiêu hóa, hạ huyết áp, giải cảm và nhiều công dụng tuyệt vời khác.',
                'price' => 10000,
                'is_actived' => true,
                'number_grow_day' => 50,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'category_id' => 1,
                'name' => 'Dấp cá',
                'description' => 'Trong dân gian còn có tên diếp cá, ngư tinh thảo, rau vẹn, tập thái. Là một loại rau rất tốt cho sức khỏe, có thể xay ra để uống trị một số bệnh như táo bón, chữa sốt cho trẻ em, ...',
                'price' => 10000,
                'is_actived' => true,
                'number_grow_day' => 40,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'category_id' => 5,
                'name' => 'Su hào',
                'description' => 'Su hào có thể ăn sống cũng như được đem luộc, nấu. Su hào chứa nhiều chất xơ tốt cho hệ tiêu hóa cũng như chứa các chất như selen, axít folic, vitamin C, kali, magiê và đồng.',
                'price' => 14000,
                'is_actived' => true,
                'number_grow_day' => 70,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'category_id' => 1,
                'name' => 'Tía tô',
                'description' => 'Rau tía tô có mùi thơm, vị cay đặc trưng, tính ấm. Đồng thời, tía tô cũng là một loại thuốc chữa bệnh và phòng bệnh theo y học cổ truyền.',
                'price' => 10000,
                'is_actived' => true,
                'number_grow_day' => 50,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'category_id' => 4,
                'name' => 'Thì là',
                'description' => 'Rau thì là là một loại rau gia vị không thể thiếu trong các món canh cá, lẩu cả, mực,… giúp khử mùi tanh, làm cho món ăn thơm ngon hơn. Ngoài tác dụng trong ẩm thực ra, rau thì là còn có nhiều tác dụng trong việc chữa trị bệnh. ',
                'price' => 7000,
                'is_actived' => true,
                'number_grow_day' => 40,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'category_id' => 4,
                'name' => 'Riềng',
                'description' => 'Riềng chứa các hoạt chất mang đặc tính kháng viêm nên rất có ích trong việc điều trị viêm khớp, thấp khớp, phong thấp, đau cơ bắp và giúp vết thương mau lành mà ít để lại sẹo. ',
                'price' => 11000,
                'is_actived' => true,
                'number_grow_day' => 60,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'category_id' => 5,
                'name' => 'Bí đao',
                'description' => 'Bí đao, bí xanh  là loại quả dùng làm thực phẩm thông dụng cho mọi gia đình, nó cũng là loại quả đa công dụng nhất. Bí đao vừa dùng để chế biến đồ ăn, thức uống, vừa được chị em tin dùng trong việc làm đẹp, giảm cân...',
                'price' => 15000,
                'is_actived' => true,
                'number_grow_day' => 70,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        DB::table('images')->insert([
            [
                'id' => 1,
                'title' => 'Cải bẹ',
                'src' => 'cai_be.jpg',
                'entityable_id' => 6,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'title' => 'Cải bẹ',
                'src' => 'cai_be2.jpg',
                'entityable_id' => 6,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'title' => 'Cải cúc',
                'src' => 'cai_cuc.jpg',
                'entityable_id' => 11,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'title' => 'Cải cúc',
                'src' => 'cai_cuc2.jpg',
                'entityable_id' => 11,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'title' => 'Cải ngồng',
                'src' => 'cai_ngong.jpg',
                'entityable_id' => 4,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'title' => 'Cải ngọt',
                'src' => 'cai_ngot.jpg',
                'entityable_id' => 5,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'title' => 'Cải ngọt',
                'src' => 'cai_ngot2.jpg',
                'entityable_id' => 5,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'title' => 'Cải thìa',
                'src' => 'cai_thia.jpg',
                'entityable_id' => 7,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'title' => 'Cải thìa',
                'src' => 'cai_thia2.jpg',
                'entityable_id' => 7,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'title' => 'Củ cải trắng',
                'src' => 'cu_cai.jpg',
                'entityable_id' => 13,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'title' => 'Củ cải trắng',
                'src' => 'cu_cai2.jpg',
                'entityable_id' => 13,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'title' => 'Riềng',
                'src' => 'cu_rieng.jpg',
                'entityable_id' => 19,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'title' => 'Riềng',
                'src' => 'cu_rieng2.jpg',
                'entityable_id' => 19,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'title' => 'Diếp cá',
                'src' => 'diep_ca.jpg',
                'entityable_id' => 15,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'title' => 'Hành lá',
                'src' => 'hanh.jpg',
                'entityable_id' => 12,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'title' => 'Hành lá',
                'src' => 'hanh2.jpg',
                'entityable_id' => 12,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'title' => 'Mồng tơi',
                'src' => 'mong_toi.jpg',
                'entityable_id' => 10,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'title' => 'Mồng tơi',
                'src' => 'mong_toi2.png',
                'entityable_id' => 10,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'title' => 'Rau kinh giới',
                'src' => 'rau_kinh_gioi.jpg',
                'entityable_id' => 9,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'title' => 'Rau kinh giới',
                'src' => 'rau_kinh_gioi2.jpg',
                'entityable_id' => 9,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'title' => 'Rau lang',
                'src' => 'rau_lang.jpg',
                'entityable_id' => 8,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'title' => 'Rau lang',
                'src' => 'rau_lang2.jpg',
                'entityable_id' => 8,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'title' => 'Rau muống',
                'src' => 'rau_muong.jpg',
                'entityable_id' => 2,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'title' => 'Rau ngót',
                'src' => 'rau_ngot.jpg',
                'entityable_id' => 3,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'title' => 'Rau ngót',
                'src' => 'rau_ngot2.jpg',
                'entityable_id' => 3,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 27,
                'title' => 'Sả',
                'src' => 'sa.jpg',
                'entityable_id' => 14,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'title' => 'Sả',
                'src' => 'sa2.jpg',
                'entityable_id' => 14,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'title' => 'Su hào',
                'src' => 'su_hao.jpeg',
                'entityable_id' => 16,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'title' => 'Su hào',
                'src' => 'su_hao2.jpg',
                'entityable_id' => 16,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 31,
                'title' => 'Thì là',
                'src' => 'thi_la.jpg',
                'entityable_id' => 18,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 32,
                'title' => 'Thì là',
                'src' => 'thi_la2.jpg',
                'entityable_id' => 18,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 33,
                'title' => 'Tía tô',
                'src' => 'tia_to.jpg',
                'entityable_id' => 17,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 34,
                'title' => 'Tía tô',
                'src' => 'tia_to2.jpg',
                'entityable_id' => 17,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 35,
                'title' => 'Xà lách',
                'src' => 'xa_lach.jpg',
                'entityable_id' => 1,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 36,
                'title' => 'Xà lách',
                'src' => 'xa_lach2.jpg',
                'entityable_id' => 1,
                'entityable_type' => Vegetable::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 37,
                'title' => 'Store 1',
                'src' => 'store_1_1.jpg',
                'entityable_id' => 1,
                'entityable_type' => Store::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 38,
                'title' => 'Store 1',
                'src' => 'store_1_2.jpg',
                'entityable_id' => 1,
                'entityable_type' => Store::class,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
        DB::table('vegetable_in_store')->insert([
            [
                'id' => 1,
                'vegetable_id' => 1,
                'store_id' => 1,
                'price' => 10000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'vegetable_id' => 2,
                'store_id' => 1,
                'price' => 10000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'vegetable_id' => 3,
                'store_id' => 1,
                'price' => 10000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'vegetable_id' => 4,
                'store_id' => 1,
                'price' => 10000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'vegetable_id' => 5,
                'store_id' => 1,
                'price' => 12000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'vegetable_id' => 6,
                'store_id' => 1,
                'price' => 10000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'vegetable_id' => 7,
                'store_id' => 1,
                'price' => 10000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'vegetable_id' => 8,
                'store_id' => 1,
                'price' => 10000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'vegetable_id' => 9,
                'store_id' => 1,
                'price' => 13000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'vegetable_id' => 10,
                'store_id' => 1,
                'price' => 14000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'vegetable_id' => 11,
                'store_id' => 1,
                'price' => 10000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'vegetable_id' => 12,
                'store_id' => 1,
                'price' => 5000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // store 2
            [
                'id' => 13,
                'vegetable_id' => 2,
                'store_id' => 2,
                'price' => 6000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'vegetable_id' => 4,
                'store_id' => 2,
                'price' => 5000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'vegetable_id' => 6,
                'store_id' => 2,
                'price' => 11000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'vegetable_id' => 7,
                'store_id' => 2,
                'price' => 12000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'vegetable_id' => 9,
                'store_id' => 2,
                'price' => 4000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //store 3
            [
                'id' => 18,
                'vegetable_id' => 1,
                'store_id' => 3,
                'price' => 3000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'vegetable_id' => 3,
                'store_id' => 3,
                'price' => 4000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'vegetable_id' => 11,
                'store_id' => 3,
                'price' => 6000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'vegetable_id' => 12,
                'store_id' => 3,
                'price' => 8000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'vegetable_id' => 10,
                'store_id' => 3,
                'price' => 11000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // store 4
            [
                'id' => 23,
                'vegetable_id' => 9,
                'store_id' => 4,
                'price' => 4000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'vegetable_id' => 7,
                'store_id' => 4,
                'price' => 9000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'vegetable_id' => 11,
                'store_id' => 4,
                'price' => 10000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'vegetable_id' => 3,
                'store_id' => 4,
                'price' => 14000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //store 5
            [
                'id' => 27,
                'vegetable_id' => 2,
                'store_id' => 5,
                'price' => 8000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'vegetable_id' => 9,
                'store_id' => 5,
                'price' => 4000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'vegetable_id' => 7,
                'store_id' => 5,
                'price' => 9000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'vegetable_id' => 6,
                'store_id' => 5,
                'price' => 12000,
                'created_at' => $now,
                'updated_at' => $now,
            ], // store 6
            [
                'id' => 31,
                'vegetable_id' => 2,
                'store_id' => 6,
                'price' => 15000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 32,
                'vegetable_id' => 11,
                'store_id' => 6,
                'price' => 2000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 33,
                'vegetable_id' => 4,
                'store_id' => 6,
                'price' => 3000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 34,
                'vegetable_id' => 6,
                'store_id' => 6,
                'price' => 7000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // store 7
            [
                'id' => 35,
                'vegetable_id' => 4,
                'store_id' => 7,
                'price' => 9000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 36,
                'vegetable_id' => 12,
                'store_id' => 7,
                'price' => 8000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 37,
                'vegetable_id' => 5,
                'store_id' => 7,
                'price' => 6000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 38,
                'vegetable_id' => 3,
                'store_id' => 7,
                'price' => 3000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // store 8
            [
                'id' => 39,
                'vegetable_id' => 6,
                'store_id' => 8,
                'price' => 2000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 40,
                'vegetable_id' => 10,
                'store_id' => 8,
                'price' => 8000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 41,
                'vegetable_id' => 7,
                'store_id' => 8,
                'price' => 9000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 42,
                'vegetable_id' => 8,
                'store_id' => 8,
                'price' => 4000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // store 9
            [
                'id' => 43,
                'vegetable_id' => 1,
                'store_id' => 9,
                'price' => 9000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 44,
                'vegetable_id' => 3,
                'store_id' => 9,
                'price' => 11000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 45,
                'vegetable_id' => 5,
                'store_id' => 9,
                'price' => 8000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 46,
                'vegetable_id' => 7,
                'store_id' => 5,
                'price' => 10000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // store 10
            [
                'id' => 47,
                'vegetable_id' => 5,
                'store_id' => 10,
                'price' => 8000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 48,
                'vegetable_id' => 10,
                'store_id' => 10,
                'price' => 7000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 49,
                'vegetable_id' => 11,
                'store_id' => 10,
                'price' => 4000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 50,
                'vegetable_id' => 2,
                'store_id' => 10,
                'price' => 2000,
                'created_at' => $now,
                'updated_at' => $now,
            ], // store 11
            [
                'id' => 51,
                'vegetable_id' => 7,
                'store_id' => 11,
                'price' => 9000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 52,
                'vegetable_id' => 8,
                'store_id' => 11,
                'price' => 9000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 53,
                'vegetable_id' => 9,
                'store_id' => 11,
                'price' => 10000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 54,
                'vegetable_id' => 2,
                'store_id' => 11,
                'price' => 9000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // store 12
            [
                'id' => 55,
                'vegetable_id' => 2,
                'store_id' => 12,
                'price' => 10000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 56,
                'vegetable_id' => 3,
                'store_id' => 12,
                'price' => 4000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 57,
                'vegetable_id' => 10,
                'store_id' => 12,
                'price' => 3000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 58,
                'vegetable_id' => 7,
                'store_id' => 12,
                'price' => 15000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 59,
                'vegetable_id' => 8,
                'store_id' => 12,
                'price' => 12000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 60,
                'vegetable_id' => 9,
                'store_id' => 12,
                'price' => 4000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 61,
                'vegetable_id' => 11,
                'store_id' => 12,
                'price' => 8000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 62,
                'vegetable_id' => 4,
                'store_id' => 12,
                'price' => 9000,
                'created_at' => $now,
                'updated_at' => $now,
            ],

        ]);

        factory(Trunk::class, 10)->create([
            'store_id' => 1,
        ])->each(function ($trunk) {
            factory(TrunkStatus::class, 5)->create([
                'trunk_id' => $trunk->id,
                'vegetable_id' => random_int(1, 15),
                'number_grow_day' => random_int(40, 80),
                'planting_day' => Carbon::now()->subDays(random_int(20, 40))->toDateTimeString(),
            ]);
        });
    }
}
